version: "3"

services:
  ssh-server:
    container_name: ssh-server
    image: jotrocken/ssh-server-pubkey
    restart: unless-stopped
    ports:
       - 4422:22
    volumes:
      - ./keys:/home/tunnel/.ssh/

