version: "3"

services:
  ssh-server:
    container_name: ssh-server
    image: jotrocken/ssh-server-pubkey
    restart: unless-stopped
    ports:
       - 4422:22
       - 4401:4401
       - 4402:4402
       - 4403:4403
    volumes:
      - ./keys:/home/tunnel/.ssh/

